@host = https://wi1ns6zxjf.execute-api.ap-southeast-1.amazonaws.com

GET {{host}}/items

###
# @name newItem
POST {{host}}/new
Content-Type: application/json

{
  "id": 1,
  "name": "Iphone14",
  "description": "Newest and fast smartphone in 2022"
}

###
PUT {{host}}/update/10
Content-Type: application/json

{
  "id": 1,
  "name": "Iphone14",
  "description": "Newest and fast smartphone in 2022"
}